Final/application/routes/auth.py
from flask import Blueprint, request, url_for, redirect, render_template, flash
from flask_login.utils import login_required, logout_user
from application.database import db
from application.models.user_mode import User
from flask_login import login_user
from werkzeug.security import generate_password_hash, check_password_hash

from flask_restful import abort
import email_validator

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template('Security/login_user.html')
    elif request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('pass')
        remember = request.form.get('remember')

        if remember is not None:
            remember = True
        
        try:
            valid = email_validator.validate_email(email)
            if valid:
                email = valid.email
                user = db.session.query(User).filter(User.email == email).first()
                if user:
                    if check_password_hash(user.password, password):
                        login_user(user, remember=remember)
                        return redirect(url_for('profile.home'))
                    else:
                        flash('Please check your login details and try again.')
                        return redirect(url_for('auth.login'))
                else:
                    new_user = User(
                        email=email,
                        password=generate_password_hash(password, method='sha256'),
                    )

                    db.session.add(new_user)

                    db.session.commit()

                    login_user(new_user, remember=remember)
                    return redirect(url_for('profile.profileFunc', isUpdate="1"))
        except Exception as e:
            flash(str(e))
            db.session.rollback()

        return redirect(url_for('auth.login'))
    else:
        abort(405, "The method is not allowed for the requested URL.")


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

Final/application/routes/profile.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from flask.helpers import flash
from flask_login import login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from application.models.response_mode import ReviewCard
from application.models.response_mode import ReviewResponse
from application.models.user_mode import User
from application.models.deck import Deck, Card
from application.database import db
from sqlalchemy.sql import func

profile = Blueprint('profile', __name__)

@profile.route('/')
@login_required
def home():
    
    isForm = request.args.get('isForm')
    flag = request.args.get('flag')
    decks = []
    
    try:
        if flag is None or flag == "0":
            decks = db.session.query(Deck).filter(Deck.public_status == True).all()
        elif flag == "1":
            decks = db.session.query(Deck).filter(Deck.public_status == True).filter(Deck.created_for.in_(i for i in Deck.Type if i.value == current_user.role.value)).all()
        elif flag == "2":
            decks = current_user.decks.all()
        elif flag == "3":
            decks = current_user.decks.filter(Deck.public_status == False).all()
        
        for i, item in enumerate(decks):
            decks[i].user = db.session.query(User).with_entities(User.name).filter(User.id == item.created_by_id).first()
            decks[i].number_of_cards = item.cards.count()
    except Exception as e:
        print(str(e))
        flash(str(e), "toast")
        decks = []

    return render_template('Deck/Deck.html', user=current_user, decks=decks, flag=flag, isForm=isForm)

@profile.route('/profile')
@login_required
def profileFunc():
    isUpdate = request.args.get('isUpdate')
    all = current_user.reviewResponses.order_by(ReviewResponse.completed_at).all()
    final = None
    final_cards= []
    remain = []

    if all:
        final = all[-1]
        final_cards = final.cards.with_entities(ReviewCard.difficulty, func.count(ReviewCard.difficulty)).group_by(ReviewCard.difficulty).all()
        final.deck = db.session.query(Deck).filter(Deck.id==final.deck_id).first()

        all.reverse()

        if len(all) > 1:
            remain = all[1:]
            
            for i,item in enumerate(remain):
                remain[i].deck = db.session.query(Deck).filter(Deck.id == item.deck_id).first()

    return render_template('Dashboard/Profile.html', user=current_user, isUpdate=isUpdate, final=final, final_cards=final_cards, decks=remain)


@profile.route('/profile/update', methods=['POST'])
@login_required
def profileUpdate():
    user = db.session.query(User).filter(User.id == current_user.id).first()
    name = request.form.get('name')
    if name:
        user.name = name
    
    
    role = request.form.get('role')
    if role:
        user.role = role
    
    currentPassword = request.form.get('currentPassword')
    if currentPassword:
        if check_password_hash(user.password, currentPassword):
            newPassword = request.form.get('newPassword')
            confirmNewPassword = request.form.get('confirmNewPassword')
            if newPassword != confirmNewPassword:
                flash('Passwords not matching', 'error')
                return redirect(url_for('profile.profileFunc', isUpdate="1"))
            
            user.password = generate_password_hash(newPassword, method='sha256')
        else:
            flash('Current password is wrong', 'error')
            return redirect(url_for('profile.profileFunc', isUpdate="1"))

    try:
        db.session.add(user)
        db.session.commit()
        flash("Profile Updated Successfully", 'toast')
        return redirect(url_for('profile.profileFunc'))
    except Exception as e:
        db.session.rollback()
        flash(str(e))
        return redirect(url_for('profile.profileFunc', isUpdate="1"))
    


@profile.route('/api/get_score/<int:user_id>', methods=['GET'])
def get_score(user_id):
    user = db.session.query(User).filter(User.id == int(user_id)).first()
    if user:
        user_score = user.review_response()
        return jsonify({
            "user_score":user_score,
        })
    return jsonify({
        "error":"User Doesn't Exist"
    })

Final/templates/Dashboard/Profile.html
{% extends 'Base.html' %}

{% block title %} Profile {% endblock %}

{% block customLinks %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/profile.css') }}" />
{% endblock %}

{% block mainContent %}
<div id="profile">

    <div class="container profileDetails">
        <h1 class="headline">Account Setting</h1>
        <div class="profileRow mb-5">
            <div class="image" align="center">
                <img src="{{ user.image if user.image else 'https://ptetutorials.com/images/user-profile.png'}}"
                    alt="{{user.name}}">
            </div>
            <div class="details">
                <h2>{{ user.name if user.name else 'Update Name' }}</h2>
                <a href="mailto:{{user.email}}" class="uniq_username">{{ user.email }}</a>
                <p>{{ user.role.name }}</p>

                <button data-bs-toggle="modal" data-bs-target="#updateProfile" class="btn updateProfile">Update
                    Profile</button>
                <a class="btn logout" href="{{ url_for('auth.logout') }}">Logout</a>
                <br>
            </div>
            <div class="badge text-center">
                <div>
                    <h1>
                        {{ user.review_response() }}%
                    </h1>
                    <p class="text-center">Average Score</p>
                </div>
            </div>
        </div>
        <hr>
        {% if final %}
        <h1 class="headline">Last Reviewed</h1>
        <div class="progress mt-3 w-75 mx-auto bg-danger" style="height:25px;">
            <div class="progress-bar bg-success" id="progressBar" role="progressbar">{{final.score}}%</div>
        </div>
        <div class="mx-auto d-block w-75">
            <div class="d-flex align-items-center w-100">
                <div class="mt-4">
                    {% if final.deck %}
                        <a href="{{ url_for('deck.view_deck', deck_id=final.deck.id) }}" class="fs-5">
                            {{ final.deck.name}}
                        </a>
                    {% else %}
                        <a href="#!" class="fs-5">Deleted Deck</a>
                    {% endif %}
                </div>
                <div class="ms-auto me-0">
                    <div class="avg_time mt-4">
                        <h3 class="fs-6">Averge time :- {{ final.avg_time }} sec</h3>
                    </div>
                    <div class="completed_at">
                        <h3 class="fs-6">Completed At :- {{ final.completed_at.strftime(" %H:%M:%S, %d/%m/%Y") }}</h3>
                    </div>
                </div>
            </div>
            
            {% if final_decks|length > 0 %}
			<div class="question_type">
                <ul>
                    {% for item in final_cards %}
                    <li class="{{ item.difficulty.name }}">
                        {{ item.difficulty.name }} - {{ item[1] }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>
        <hr>
        {% endif %}
        {% if decks|length > 0 %}

        <h1 class="headline">All Reviewed</h1>
        <table class="table text-center">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Tag</th>
                    <th scope="col">Score</th>
                    <th scope="col">Avg Time</th>
                </tr>
            </thead>
            <tbody class="fs-6">
                {% for item in decks %}
                <tr>
                    <th scope="row">1</th>
                    <td style="text-align: left;">
                        <a href="{{ url_for('deck.view_deck', deck_id=item.deck.id) }}" class="fs-6 mt-0">
                            {{ item.deck.name }}
                        </a>
                    </td>
                    <td>{{ item.deck.created_for.name }}</td>
                    <td>{{ item.score }}</td>
                    <td>{{ item.avg_time }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}
        <div class="modal fade" id="updateProfile" aria-labelledby="updateProfileLabel" aria-hidden="true"
            tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Update Profile</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form name="updateForm" class="needs-validation" novalidate
                        action="{{ url_for('profile.profileUpdate') }}" method="POST">
                        <div class="modal-body">
                            {% with messages = get_flashed_messages(category_filter=["error"]) %}
                            {% if messages %}
                            {%- for msg in messages %}
                            <div class="text-danger">
                                {{ msg }}
                            </div>
                            {% endfor -%}
                            {% endif %}
                            {% endwith %}
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name"
                                    value="{{user.name if user.name else ''}}">
                            </div>
                            <div class="mb-3 d-flex justify-content-evenly">
                                <div>
                                    <input class="form-check-input" type="radio" name="role" value="STUDENT" {% if
                                        user.role.value=="1" %}checked{% endif %} id="student">
                                    <label class="form-check-label" for="student">
                                        Student
                                    </label>
                                </div>
                                <div>
                                    <input class="form-check-input" type="radio" name="role" value="TEACHER" {% if
                                        user.role.value=="2" %}checked{% endif %} id="teacher">
                                    <label class="form-check-label" for="teacher">
                                        Teacher
                                    </label>
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Email address</label>
                                <input type="email" class="form-control" id="exampleInputEmail1"
                                    aria-describedby="emailHelp" name="email" readonly disabled
                                    placeholder="abcd@abcd.com" value="{{user.email}}" required>
                            </div>
                            <div class="mb-3">
                                <label for="currentPassword" class="form-label">Current Password</label>
                                <input type="password" name="currentPassword" class="form-control" id="currentPassword"
                                    minlength="8" maxlength="20" placeholder="**********">
                                <div class="invalid-feedback">
                                    Please enter valid password
                                    Must be 8-20 characters long.
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="newPassword" class="form-label">New Password</label>
                                <input type="password" name="newPassword" class="form-control" id="newPassword"
                                    minlength="8" maxlength="20" placeholder="**********">
                                <div class="invalid-feedback">
                                    Please enter valid password
                                    Must be 8-20 characters long.
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="confirmNewPassword" class="form-label">Confirm New Password</label>
                                <input type="password" name="confirmNewPassword" class="form-control"
                                    id="confirmNewPassword" minlength="8" maxlength="20" placeholder="**********">
                                <div class="invalid-feedback">
                                    Please enter valid password
                                    Must be 8-20 characters long.
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scriptsLinks %}
<script>

    if ($("#progressBar"))
        $("#progressBar").css("width", "{{final.score}}%");

    var myModal = new bootstrap.Modal(document.getElementById('updateProfile'), {})
    if ("{{isUpdate}}" === "1") {
        myModal.show()
    }

    var empty = "Must Not Be Empty";
    var notMatch = "Password Not Matching"

    var forms = document.querySelector('form[name="updateForm"]')
    forms.addEventListener('submit', function (event) {
        if (!forms.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
        }

        let currentPassword = forms['currentPassword'].value

        if (currentPassword) {
            let newPassword = forms['newPassword'].value
            let confirmNewPassword = forms['confirmNewPassword'].value
            if (!(newPassword !== '' && confirmNewPassword !== '' && newPassword === confirmNewPassword)) {
                event.preventDefault()
                event.stopPropagation()
                if (newPassword === "" || confirmNewPassword === "") {

                    if (newPassword === "") {
                        forms['newPassword'].classList.add('is-invalid')
                        forms['newPassword'].setCustomValidity('Empty Not Valid')
                        forms['newPassword'].parentElement.querySelector('.invalid-feedback').innerHTML = empty
                    }
                    if (confirmNewPassword === "") {
                        forms['confirmNewPassword'].parentElement.querySelector('.invalid-feedback').innerHTML = empty
                        forms['confirmNewPassword'].classList.add('is-invalid')
                        forms['confirmNewPassword'].setCustomValidity('Empty Not Valid')
                    }

                }
                else if (newPassword !== confirmNewPassword) {
                    forms['confirmNewPassword'].classList.add('is-invalid')
                    forms['confirmNewPassword'].setCustomValidity('Password not match')
                    forms['confirmNewPassword'].parentElement.querySelector('.invalid-feedback').innerHTML = notMatch
                }
            } else {
                forms['newPassword'].classList.add('is-valid')
                forms['newPassword'].setCustomValidity('')
                forms['confirmNewPassword'].classList.add('is-valid')
                forms['confirmNewPassword'].setCustomValidity('')
            }
        }
        forms.classList.add('was-validated')
    }, false)
</script>
{% endblock %}