Final/application/routes/profile.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from flask.helpers import flash
from flask_login import login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from application.models.response_mode import ReviewCard
from application.models.response_mode import ReviewResponse
from application.models.user_mode import User
from application.models.deck import Deck, Card
from application.database import db
from sqlalchemy.sql import func

profile = Blueprint('profile', __name__)

@profile.route('/')
@login_required
def home():
    
    isForm = request.args.get('isForm')
    flag = request.args.get('flag')
    decks = []
    
    try:
        if flag is None or flag == "0":
            decks = db.session.query(Deck).filter(Deck.public_status == True).all()
        elif flag == "1":
            decks = db.session.query(Deck).filter(Deck.public_status == True).filter(Deck.created_for.in_(i for i in Deck.Type if i.value == current_user.role.value)).all()
        elif flag == "2":
            decks = current_user.decks.all()
        elif flag == "3":
            decks = current_user.decks.filter(Deck.public_status == False).all()
        
        for i, item in enumerate(decks):
            decks[i].user = db.session.query(User).with_entities(User.name).filter(User.id == item.created_by_id).first()
            decks[i].number_of_cards = item.cards.count()
    except Exception as e:
        print(str(e))
        flash(str(e), "toast")
        decks = []

    return render_template('Deck/Deck.html', user=current_user, decks=decks, flag=flag, isForm=isForm)

@profile.route('/profile')
@login_required
def profileFunc():
    isUpdate = request.args.get('isUpdate')
    all = current_user.reviewResponses.order_by(ReviewResponse.completed_at).all()
    final = None
    final_cards= []
    remain = []

    if all:
        final = all[-1]
        final_cards = final.cards.with_entities(ReviewCard.difficulty, func.count(ReviewCard.difficulty)).group_by(ReviewCard.difficulty).all()
        final.deck = db.session.query(Deck).filter(Deck.id==final.deck_id).first()

        all.reverse()

        if len(all) > 1:
            remain = all[1:]
            
            for i,item in enumerate(remain):
                remain[i].deck = db.session.query(Deck).filter(Deck.id == item.deck_id).first()

    return render_template('Dashboard/Profile.html', user=current_user, isUpdate=isUpdate, final=final, final_cards=final_cards, decks=remain)


@profile.route('/profile/update', methods=['POST'])
@login_required
def profileUpdate():
    user = db.session.query(User).filter(User.id == current_user.id).first()
    name = request.form.get('name')
    if name:
        user.name = name
    
    
    role = request.form.get('role')
    if role:
        user.role = role
    
    currentPassword = request.form.get('currentPassword')
    if currentPassword:
        if check_password_hash(user.password, currentPassword):
            newPassword = request.form.get('newPassword')
            confirmNewPassword = request.form.get('confirmNewPassword')
            if newPassword != confirmNewPassword:
                flash('Passwords not matching', 'error')
                return redirect(url_for('profile.profileFunc', isUpdate="1"))
            
            user.password = generate_password_hash(newPassword, method='sha256')
        else:
            flash('Current password is wrong', 'error')
            return redirect(url_for('profile.profileFunc', isUpdate="1"))

    try:
        db.session.add(user)
        db.session.commit()
        flash("Profile Updated Successfully", 'toast')
        return redirect(url_for('profile.profileFunc'))
    except Exception as e:
        db.session.rollback()
        flash(str(e))
        return redirect(url_for('profile.profileFunc', isUpdate="1"))
    


@profile.route('/api/get_score/<int:user_id>', methods=['GET'])
def get_score(user_id):
    user = db.session.query(User).filter(User.id == int(user_id)).first()
    if user:
        user_score = user.review_response()
        return jsonify({
            "user_score":user_score,
        })
    return jsonify({
        "error":"User Doesn't Exist"
    })

Final/application/routes/review.py
from datetime import datetime
from pytz import timezone
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session
from flask_restful import  reqparse
from flask.helpers import flash
from flask_login import login_required, current_user
from application.error import APIException
from application.database import db
from application.models.deck import Card
from application.models.response_mode import ReviewCard, ReviewResponse
from application.routes.deck import get_all_cards as deck_get_all_cards, get as deck_get
from sqlalchemy.exc import IntegrityError
from sqlalchemy.sql import func

review = Blueprint('review', __name__)


review_req = reqparse.RequestParser()
review_req.add_argument("difficulty")
review_req.add_argument("next")
review_req.add_argument("response_id")

@review.route('/start_test/<int:deck_id>', methods=["GET"])
@login_required
def review_form(deck_id):
    deck = None
    card = None
    isFinish = False
    next_card = request.args.get('next_card') 
    final_cards = []
    final = {}
    if not next_card:
        next_card = 0
    else:
        next_card = int(next_card)
    try:
        
        deck=deck_get(deck_id)
        cards = deck_get_all_cards(deck_id)

        try:
            response_curr = db.session.query(ReviewResponse).filter(ReviewResponse.user_id == current_user.id).filter(ReviewResponse.deck_id == int(deck_id)).first()
            if response_curr:
                if response_curr.cards.count() == len(cards):
                    isFinish = True
                    final = response_curr
                    final_cards = response_curr.cards.with_entities(ReviewCard.difficulty, func.count(ReviewCard.difficulty)).group_by(ReviewCard.difficulty).all()
                    print(final_cards)
                else:
                    session['review_respose_id'] = response_curr.id

            else:
                new_response = ReviewResponse(
                    score = 0,
                    avg_time = 0,
                    user_id = int(current_user.id),
                    deck_id = int(deck_id),
                )
                db.session.add(new_response)
                db.session.commit()
                session['review_respose_id'] = new_response.id

        except Exception as e:
            flash(str(e), 'toast')

        if next_card + 1 > len(cards):
            isFinish = True
        else:
            card = cards[next_card]
            card['next'] = next_card + 1
        
        
    except Exception as e:
        print(str(e))
        flash(str(e), 'toast')

    return render_template("Review/Review.html", user=current_user, deck=deck, card=card, isFinish=isFinish, final=final, final_cards=final_cards)


@review.route('/next_test/<int:deck_id>', methods=["POST"])
@login_required
def review_form_post(deck_id):
    
    if request.method == "POST":
        try:
            
            args = review_req.parse_args()
            difficulty = args.get("difficulty", None)
            next_card = int(args.get("next", None))
            response_id = args.get("response_id", None)

            review_res_curr = db.session.query(ReviewCard).filter(ReviewCard.id == response_id).first()
            
            if review_res_curr:
                review_res_curr.difficulty = ReviewCard.Diffculty(difficulty).name

                db.session.add(review_res_curr)
                db.session.commit()

            
            response_curr = db.session.query(ReviewResponse).filter(ReviewResponse.user_id == current_user.id).filter(ReviewResponse.deck_id == int(deck_id)).first()
            if response_curr:
                response_curr.score = round((response_curr.cards.filter(ReviewCard.correct == True).count()/response_curr.cards.count()) * 100, 2)
                
                response_curr.avg_time = response_curr.avg_time_count()/response_curr.cards.count()

                response_curr.completed_at = datetime.now(timezone('Asia/Kolkata'))
                
                db.session.add(response_curr)
                db.session.commit()

            return redirect(url_for('review.review_form', deck_id=deck_id, next_card=next_card))
        except Exception as e:
            flash(str(e), 'toast')
    
    redirect(url_for('review.review_form', deck_id=deck_id, next_card=0))


@review.route('/review/check_answer')
@login_required
def check_answer():
    
    card_id = request.args.get('card_id')
    answer = request.args.get('answer')
    time_take = request.args.get('time')
    
    correct = False
    try:
        if card_id is None or not isinstance(card_id, str):
            raise APIException("400","card_id is required.")
        
        card = db.session.query(Card).filter(Card.id == int(card_id)).first()
        
        if answer == "" or answer is None or not isinstance(answer, str):
            raise APIException("400","Answer is required")
        
        if time_take == "" or time_take is None or not isinstance(time_take, str):
            raise APIException("400","time_take is required")

        if str(card.back).lower() == answer.strip().lower():
            correct = True
        
        curr_response = db.session.query(ReviewCard).filter(ReviewCard.card_id == int(card_id)).filter(ReviewCard.review_respose_id == int(session['review_respose_id'])).first()

        if curr_response:
            curr_response.selected_option = answer
            curr_response.time = int(time_take)
            curr_response.correct = correct
            db.session.add(curr_response)
            new_id=curr_response.id
        else:
            new_response = ReviewCard(
                correct_option = str(card.back),
                selected_option = answer,
                time = int(time_take),
                correct = correct,
                card_id = int(card_id),
                review_respose_id = int(session['review_respose_id'])
            )

            db.session.add(new_response)
            new_id = new_response.id
        db.session.commit()

        res = {
            "correct":correct,
            "answer":card.back,
            "response_id":new_id
        }
    except IntegrityError as e:
        res = {
            "correct":False,
            "answer":None,
            "error":str(e),
            "redirect":True,
        }
    except Exception as e:
        res = {
            "correct":False,
            "answer":None,
            "error":str(e)
        }

    return jsonify(res)

Final/templates/Review/Review.html
{% extends 'Base.html' %}

{% block title %} {{deck.name}} {% endblock %}

{% block customLinks %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/review.css') }}" />
{% endblock %}

{% block mainContent %}
<div id="review">
    <div class="container-sm w-75 bg-light p-2 pb-5 mt-5">

        {% if isFinish %}
            <h1 class="text-center fs-4 mt-5">Congratulations! You have completed the deck!</h1>
            <div class="progress mt-5 w-75 mx-auto bg-danger" style="height:25px;">
                <div class="progress-bar bg-success" id="progressBar" role="progressbar">{{final.score}}%</div>
            </div>
            <div class="mx-auto d-block w-75">
                <div class="avg_time mt-4">
                    <h3 class="fs-5">Averge time :- {{ final.avg_time }} sec</h3>
                </div>
                <div class="completed_at">
                    <h3 class="fs-5">Completed At :- {{ final.completed_at.strftime(" %H:%M:%S, %d/%m/%Y") }}</h3>
                </div>
                <div class="question_type">
                    <ul>
                        {% for item in final_cards %}
                            <li class="{{ item.difficulty.name }}">
                                {{ item.difficulty.name }} - {{ item[1] }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <a href="{{ url_for('profile.home') }}" class="btn btn-primary mx-auto mt-5 d-block w-50">
                    Go Home
                </a>
            </div>
        {% else %}
            <h6 class="time fs-5 text-center d-block ms-auto"></h6>
            <div class="question_card">
                <h1 class="text-center">
                    {{card.front}}
                    <span id="answer"></span>
                </h1>
            </div>
            <ul class="list-group">
                {% for option in card.options %}
                {%- if option -%}
                <li class="list-group-item">
                    <input class="form-check-input" type="radio" name="_{{card.id}}" value="{{-option-}}"
                        id="{{option}}_{{loop.index}}">
                    <label class="form-check-label" for="{{option}}_{{loop.index}}">
                        {{option}}
                    </label>
                </li>
                {%- endif -%}
                {% endfor %}
            </ul>
            <button onclick="return submitAnswer()" class="btn btn-primary w-25 mx-auto mt-3 d-block">
                <span id="submit_text">
                    Show answer
                </span>
                <div class="spinner-border d-none spinner-border-sm" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </button>

            <form action="{{ url_for('review.review_form_post', deck_id=deck.id) }}" class="d-none" name="afterSubmit" method="POST">
                <input type="text" name="next" id="next" value="{{card.next}}" hidden>
                <input type="text" name="response_id" id="response_id" hidden>
                <div class="sort_options">
                    <h5 class="d-block w-100 text-center">
                        Difficulty Level
                    </h5>
                    <div class="sorts mx-auto w-100">
                        <div class="option">
                            <input type="radio" name="difficulty" id="easy" value="1" hidden />
                            <label for="easy" class="shadow">
                                <span>Easy</span>
                            </label>
                        </div>
                        <div class="option">
                            <input type="radio" name="difficulty" id="modarate" value="2" checked hidden />
                            <label for="modarate" class="shadow">
                                <span>Moderate</span>
                            </label>
                        </div>
                        <div class="option">
                            <input type="radio" name="difficulty" id="hard" value="3" hidden />
                            <label for="hard" class="shadow">
                                <span>Hard</span>
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Next <iclass="fas fa-chevron-right"></i></button>
                    </div>
                </div>
            </form>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block scriptsLinks %}
<script>

    if($("#progressBar"))
        $("#progressBar").css("width","{{final.score}}%");

    var expected = 1;
    var prev = 0
        
    var timeh6 = $('.time')
    if(timeh6){
        timeh6.text(expected + " sec")

        var interval = setInterval(() => {
            prev= expected
            expected += 1
            timeh6.text(expected + " sec")
        }, 1000);
    }

    
    var forms = document.querySelector('form[name="afterSubmit"]')

    function submitAnswer(e) {
        var input = $(':radio[name=_{{card.id}}]').filter(':checked').val();

        if(!input){
            return false
        }

        clearInterval(interval)
        
        document.querySelector('#submit_text').classList.add('d-none')
        document.querySelector('.spinner-border ').classList.remove('d-none')
        var question_card = document.querySelector('.question_card')

        $.ajax({
            method: "GET",
            url: '{{ url_for("review.check_answer") }}?card_id={{card.id}}&&time='+ prev + '&&answer='+input,
            dataType: 'json',
            async: false,
            success: function(data){
                console.log("success");
                if(data.redirect){
                    return window.location.href = "/start_test/{{deck.id}}"
                }
                if(data.correct){
                    question_card.classList.add('bg-success')
                }else{
                    question_card.classList.add('bg-danger')
                }
            
                question_card.classList.add('show-answer')
                
                document.querySelector('#answer').innerHTML = data.answer
                $(':radio[name=_{{card.id}}]').prop('disabled', true)
                document.querySelector('#submit_text').parentElement.remove()
                document.querySelector('form[name="afterSubmit"]').classList.remove('d-none')

                forms.querySelector('[name="response_id"]').value = data.response_id
            },
            failure: function(data){
                console.log("failure");
                
                document.querySelector('#submit_text').classList.remove('d-none')
                document.querySelector('.spinner-border ').classList.add('d-none')
            },
            
        });

    }
    if(forms){
        forms.addEventListener('submit', function (event) {
            if (!forms.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
            }
            forms.classList.add('was-validated')
        }, false)
    }
</script>
{% endblock %}