Final/application/models/deck.py
from datetime import datetime
from pytz import timezone
import enum
from application.database import db
from application.models.user_mode import User

Base = db.Model

class Deck(Base):    
    
    
    class Type(enum.Enum):
        STUDENT = "1"
        TEACHER = "2"
        ALL = "3"

    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.now(timezone('Asia/Kolkata')))
    created_by_id = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)
    created_for = db.Column(db.Enum(Type))
    public_status = db.Column(db.Boolean, default=True)
    
    cards = db.relationship("Card", cascade="all,delete", backref="deck", lazy='dynamic')

class Card(Base):
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    front = db.Column(db.String, nullable = False)
    back = db.Column(db.String, nullable = False)
    options = db.Column(db.String, nullable = False)
    created_at = db.Column(db.DateTime, default=datetime.now(timezone('Asia/Kolkata')))
    created_by_id = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)
    deck_id = db.Column(db.Integer, db.ForeignKey(Deck.id, ondelete='CASCADE'), nullable=False)

    
    def serialize(self):
        """Return object data in easily serializable format"""
        return {
            'id'         : self.id,
            'options'    : self.options.split(','),
            'front'      : self.front,
            'back'       : self.back,
            'deck_id'    : self.deck_id,
            'created_by_id'  : self.created_by_id
        }

    def serialize_list(l):
        return [m.serialize() for m in l]
    

Final/application/routes/card.py
from flask import Blueprint, abort, json, render_template, request, redirect, url_for, flash, Response, send_file
from flask_restful import Resource, marshal_with, fields, reqparse, Api
from application.models.user_mode import User
from application.models.deck import Deck, Card
from application.database import db
from application.error import APIException
from sqlalchemy.exc import IntegrityError
from flask_login import login_required, current_user
from application.routes.deck import get_all_cards, get as deck_get
from io import BytesIO
import pandas as pd

card = Blueprint('card', __name__)


card_output_fields = {
    "id": fields.Integer,
    "front": fields.String,
    "back": fields.String,
    "options": fields.String,
    "created_at":fields.DateTime,
    "created_by_id": fields.Integer,
    "deck_id":fields.Integer,
}



card_red = reqparse.RequestParser()
card_red.add_argument("front")
card_red.add_argument("back")
card_red.add_argument("options")
card_red.add_argument("deck_id")
card_red.add_argument("user_id")


@card.route('/api/card/<int:card_id>', methods=['GET', 'PUT', "DELETE"])
def api_deck(card_id):
    if request.method == "GET":
        return api_get(card_id)
    elif request.method == "PUT":
        return api_put(card_id)
    elif request.method == "DELETE":
        return delete(card_id)

@marshal_with(card_output_fields)
def api_get(card_id):
    data = get(card_id)
    data.options = ",".join(data.options)
    return data, 200

#API GET
def get(card_id):
    card_curr = db.session.query(Card).filter(Card.id == int(card_id)).first()
    if card_curr:
        card_curr.deck = db.session.query(Deck).filter(Deck.id == card_curr.deck_id).first()
        if(card_curr.options):
            card_curr.options = card_curr.options.split(',')
        return card_curr
    else:
        raise APIException("404", "Card not found")

#API Delete
def delete(card_id):

    card_curr = db.session.query(Card).filter(Card.id == int(card_id) and Card.created_by_id==current_user.id).first()

    if card_curr is None:
        raise APIException(404, "Card not found")

    db.session.delete(card_curr)
    db.session.commit()

    return Response("Successfully Deleted", 200)

#API PUT
@marshal_with(card_output_fields)
def api_put(card_id):
    return put(card_id), 200
    
def put(card_id):
	args = card_red.parse_args()
	front = args.get("front", None)
	back = args.get("back", None)
	options = args.get("options", None)
	deck_id = args.get("deck_id", None)

	if front == "" or front is None or not isinstance(front, str):
		raise APIException("400","Front is required.")

	if back == "" or back is None or not isinstance(back, str):
		raise APIException("400","Back is required.")

	if options == "" or options is None or not isinstance(options, str) or options.isnumeric():
		raise APIException("400","Options should be string.")

	card_curr = db.session.query(Card).filter(Card.id == int(card_id)).first()

	if card_curr is None:
		raise APIException("404", "Card not found")

	card_curr.front = front
	card_curr.back = back

	card_curr.options = options

	if deck_id:
		card_curr.deck_id = int(deck_id)
	try:

		db.session.add(card_curr)
		db.session.commit()

		return card_curr
	except IntegrityError:
		raise APIException("400", "Card already exists")
	except Exception as e:
		raise APIException("400", str(e))


#API POST

@card.route('/api/card', methods=["POST"])
@marshal_with(card_output_fields)
def post():
    args = card_red.parse_args()
    front = args.get("front", None)
    back = args.get("back", None)
    options = args.get("options", None)
    deck_id = args.get("deck_id", None)
    user_id = args.get("user_id", None)

    if front == "" or front is None or not isinstance(front, str):
        raise APIException("400","Front is required.")
    
    if back == "" or back is None or not isinstance(back, str):
        raise APIException("400","Back is required.")
    
    if options == "" or options is None or not isinstance(options, str) or options.isnumeric():
        raise APIException("400","Options should be string.")
    
    try:

        user = current_user.id if current_user.is_active else user_id
        new_card = Card(
            front=front,
            back= back, 
            options = options,
            deck_id=int(deck_id), 
            created_by_id=user
        )

        db.session.add(new_card)
        db.session.commit()

        return new_card, 201
    except Exception as e:
        raise APIException("400", str(e))


#Get Deck with Login
@card.route('/view_card/<int:card_id>')
@login_required
def view_card(card_id):
    data = None
    try:
        data=get(card_id)
    except APIException as e:
        flash(str(e), 'toast')
    return redirect(url_for('deck.view_deck', deck_id=data.deck_id))


@card.route('/add_card', methods=["GET", "POST"])
@login_required
def add_card():
    deck_id = request.args.get('deck_id')
    if request.method == "POST":
        try:
            data = post()
            flash("Successfully Added Card", "toast")
        except APIException as e:
            flash(str(e), 'toast')
    
    if deck_id:
        deck_id = int(deck_id)
    return render_template('Deck/Add_Card.html', user=current_user, deck_id=deck_id)


@card.route('/add_card/<int:card_id>', methods=["GET", "POST"])
@login_required
def edit_card(card_id):
    if request.method == "POST":
        try:
            data = put(card_id)
            return redirect(url_for('deck.view_deck', deck_id=data.deck_id))
        except APIException as e:
            flash(str(e), 'toast')

    card = get(card_id)
    if(card.options):
        card.options = ",".join(card.options)
    return render_template('Deck/Add_Card.html', user=current_user, card=card)


@card.route('/delete_card/<int:deck_id>/<int:card_id>', methods=["GET", "POST"])
@login_required
def delete_card(card_id, deck_id):
    try:
        msg = delete(card_id)
        flash("Successfully Deleted Card", "toast")
    except APIException as e:
        flash(str(e), 'toast')

    return redirect(url_for('deck.view_deck', deck_id=deck_id))


@card.route('/import_card/<int:deck_id>', methods=["POST"])
@login_required
def import_card(deck_id):
    try:
        file = request.files.get('importFile')
        excel = pd.read_excel(file)
        skipped_rows = 0
        for i, item in excel.iterrows():
            try:  
                front = item['front']
                back = item['back']
                options = item['options']
                if front == "" or front is None:
                    raise Exception("Front is necessay")
                
                if back == "" or back is None:
                    raise Exception("Back is required.")
                
                if options == "" or options is None or not isinstance(options, str):
                    raise Exception("Options are required and should be string.")

                user = current_user.id
                new_card = Card(
                    front=front,
                    back= back, 
                    options = options,
                    deck_id=int(deck_id), 
                    created_by_id=user
                )

                db.session.add(new_card)
                db.session.commit()

            except Exception as e:
                print(str(e))
                skipped_rows += 1

        flash(f'Successfully Added Cards. Skipped Rows {skipped_rows}' , "toast")
    except APIException as e:
        flash(str(e), 'toast')

    return redirect(url_for('deck.view_deck', deck_id=deck_id))


@card.route('/download_card/<int:deck_id>')
@login_required
def download_excel(deck_id):
    try:
        deck = deck_get(deck_id)
        cards = get_all_cards(deck_id)
        df = pd.DataFrame.from_dict(cards)
        df = df.drop(['id', 'deck_id', 'created_by_id'], axis=1)
        output = BytesIO()
        writer = pd.ExcelWriter(output, engine="xlsxwriter")
        df.to_excel(writer, sheet_name='Sheet1')
        writer.save()
        output.seek(0)
        return send_file(output, attachment_filename=f'{deck.name} cards.xlsx', as_attachment=True)
    except Exception as e:
        flash(str(e), 'toast')

    return redirect(url_for('deck.view_deck', deck_id=deck_id))

Final/application/routes/deck.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, Response, jsonify
from flask_restful import Resource, marshal_with, fields, reqparse, Api
from application.models.user_mode import User
from application.models.deck import Deck,Card
from application.database import db
from application.error import APIException
from sqlalchemy.exc import IntegrityError
from flask_login import login_required, current_user

deck_output_fields = {
    "id": fields.Integer,
    "name": fields.String,
    "created_for": fields.String([x.name for x in User.Role]),
    "public_status": fields.Boolean,
    "created_at":fields.DateTime,
    "created_by_id": fields.Integer
}



deck_req = reqparse.RequestParser()
deck_req.add_argument("name")
deck_req.add_argument("public_status")
deck_req.add_argument("user_id")
deck_req.add_argument("created_for")


deck = Blueprint('deck', __name__)

@deck.route('/api/deck/<int:deck_id>', methods=['GET', 'PUT', "DELETE"])
def api_deck(deck_id):
    if request.method == "GET":
        return api_get(deck_id)
    elif request.method == "PUT":
        return api_put(deck_id)
    elif request.method == "DELETE":
        return delete(deck_id)

@marshal_with(deck_output_fields)
def api_get(deck_id):
    return get(deck_id), 200

#API GET
def get(deck_id):
    deck_curr = db.session.query(Deck).filter(Deck.id == int(deck_id)).first()
    if deck_curr:
        deck_curr.user = db.session.query(User).with_entities(User.name).filter(User.id == deck_curr.created_by_id).first()
        deck_curr.number_of_cards = deck_curr.cards.count()
        return deck_curr
    else:
        raise APIException("404", "Deck not found")

#API Delete
def delete(deck_id):

    deck_curr = db.session.query(Deck).filter(Deck.id == int(deck_id) and Deck.created_by_id==current_user.id).first()

    if deck_curr is None:
        raise APIException(404, "Deck not found")

    db.session.delete(deck_curr)
    db.session.commit()

    return Response("Successfully Deleted", 200)

#API PUT
@marshal_with(deck_output_fields)
def api_put(deck_id):
    return put(deck_id), 200
    
def put(deck_id):
    args = deck_req.parse_args()
    name = args.get("name", None)
    public_status = args.get("public_status", None)
    created_for = args.get("created_for", None)

    if name == "" or name is None or not isinstance(name, str) or name.isnumeric():
        raise APIException("400","Deck Name is required and should be string.")
    
    deck_curr = db.session.query(Deck).filter(Deck.id == int(deck_id) and Deck.created_by_id==current_user).first()

    if deck_curr is None:
        raise APIException("404", "Deck not found")

    deck_curr.name = name

    if public_status:
        deck_curr.public_status = bool(int(public_status))

    if created_for:
        deck_curr.created_for = created_for
    else:
        deck_curr.created_for = "ALL"


    try:
        
        db.session.add(deck_curr)
        db.session.commit()

        return deck_curr
    except IntegrityError:
        raise APIException("400", "Deck name already exists")
    except Exception as e:
        raise APIException("400", str(e))


@deck.route('/api/deck_cards/<int:deck_id>')
def api_get_all_cards(deck_id):
    return jsonify(get_all_cards(deck_id)), 200


def get_all_cards(deck_id):
    deck = None
    try:
        deck=get(deck_id)
        cards = deck.cards.all()
        return Card.serialize_list(cards)
    except Exception as e:
        raise APIException("400", str(e))

#API POST

@deck.route('/api/deck', methods=["POST"])
@marshal_with(deck_output_fields)
def post():
    args = deck_req.parse_args()
    name = args.get("name", None)
    public_status = args.get("public_status", None)
    user_id = args.get("user_id", None)
    created_for = args.get("created_for", None)

    if name == "" or name is None or not isinstance(name, str) or name.isnumeric():
        raise APIException("400","Deck Name is required and should be string.")

    if user_id is None or not isinstance(user_id, str):
        raise APIException("400","User id is required.")

    deck_curr = db.session.query(Deck).filter(Deck.name == name).first()

    if deck_curr:
        raise APIException("409", "Deck already exist")

    if created_for and (not isinstance(created_for, str) or created_for.isnumeric()):
        raise APIException("400","Deck Created for should be string.")

    user_curr = db.session.query(User).filter(User.id == int(user_id)).first()

    if user_curr is None:
        raise APIException("404", "User not found")
    
    try:
        
        new_deck = Deck(
            name=name,
            public_status=bool(int(public_status)), 
            created_by_id=int(user_id), 
            created_for=(created_for or "ALL")
        )

        db.session.add(new_deck)
        db.session.commit()

        return new_deck, 201
    except Exception as e:
        raise APIException("400", str(e))


#Get Deck with Login
@deck.route('/view_deck/<int:deck_id>')
@login_required
def view_deck(deck_id):
	deck = None
	try:
		deck=get(deck_id)
		cards = get_all_cards(deck_id)
	except APIException as e:
		flash(str(e), 'toast')
		if not deck:
			flash("No Deck Found", "toast")
			return redirect(url_for('profile.home'))
	return render_template("Deck/Card.html", user=current_user, deck=deck, cards=cards)


#Adding Deck With Login Required
@deck.route('/add_deck', methods=["POST"])
@login_required
def add_deck():
    if request.method == "POST":

        try:
            data = post()
            return redirect(url_for('deck.view_deck', deck_id=data[0]['id']))
        except APIException as e:
            flash(str(e), 'toast')
                

        return redirect(url_for('profile.home', isForm="1"))
        
    return redirect(url_for('profile.home'))


#Delete with Login

@deck.route('/delete_deck/<int:deck_id>')
@login_required
def delete_deck(deck_id):
    try:
        msg = delete(deck_id)
        flash("Successfully Deleted Deck", "toast")
        return redirect(url_for('profile.home'))
    except APIException as e:
        flash(str(e), 'toast')

    return redirect(url_for('deck.view_deck', deck_id=deck_id))


@deck.route('/update_deck/<int:deck_id>', methods=["POST"])
@login_required
def update_deck(deck_id):
    if request.method == "POST":

        try:
            data = put(deck_id)
            return redirect(url_for('deck.view_deck', deck_id=data.id))
        except APIException as e:
            flash(str(e), 'toast')

        return redirect(url_for('deck.view_deck', deck_id=deck_id))
        
    return redirect(url_for('deck.view_deck', deck_id=deck_id))

Final/templates/Deck/Add_Card.html
{% extends 'Base.html' %}

{% block title %} Add Card {% endblock %}

{% block customLinks %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/add_card.css') }}" />
{% endblock %}

{% block mainContent %}
<div id="add_card">
    <div class="container add_cardDetails">
        {% if user.decks.all()|length == 0 %}
            <h1 class="fs-4">
                Please add a deck from 
                <a style="color: #0d6efd;" href="{{url_for('profile.home')}}">here</a> to continue
            </h1>
        {% else %}
        <form name="addForm" class="needs-validation" novalidate
            action="{{url_for('card.edit_card', card_id=card.id) if card else url_for('card.add_card') }}" method="POST">
            <div class="modal-body">
                <div class="mb-3">
                    <label for="deck" class="form-label">Deck</label>
                    <select class="form-select" id="deck" name="deck_id" aria-label="Deck" required>
                        {% for deck in user.decks %}
                            <option value="{{deck.id}}" {% if (card and card.deck_id==deck.id) or deck_id==deck.id %}selected{%endif%}>{{deck.name}}</option>
                        {% endfor %}
                    </select>
                    <div class="invalid-feedback">
                        Please enter valid input
                    </div>
                </div>
                <div class="mb-3">
                    <label for="front" class="form-label">Front</label>
                    <input type="text" class="form-control" id="front" name="front" value="{{ card.front if card }}" placeholder="Enter front" required>
                    <div class="invalid-feedback">
                        Please enter valid input
                    </div>
                </div>
                <div class="mb-3">
                    <label for="back" class="form-label">Back</label>
                    <input type="text" class="form-control" id="back" name="back" value="{{ card.back if card }}" placeholder="Enter Back" required>
                    <div class="invalid-feedback">
                        Please enter valid input
                    </div>
                </div>
                <div class="mb-3">
                    <label for="options" class="form-label">Options</label>
                    <textarea class="form-control" id="options" name="options" rows="3"  required>{{ card.options if card and card.options else "" }}</textarea>
                    <div class="helpText">
                        Separate by comma ","
                    </div>
                    <div class="invalid-feedback">
                        Please enter options
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="{{url_for('deck.view_deck', deck_id=card.deck_id) if card else url_for('profile.home') }}" class="btn btn-secondary">Close</a>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
        {%endif%}
    </div>
</div>
{% endblock %}

{% block scriptsLinks %}
<script>


    var forms = document.querySelector('form[name="addForm"]')
    if(forms){
        forms.addEventListener('submit', function (event) {
            if (!forms.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
            }
            forms.classList.add('was-validated')
        }, false)
    }
</script>
{% endblock %}

Final/templates/Deck/Card.html
{% extends 'Base.html' %}

{% block title %} {{ deck.name if deck else "Not Found" }} {% endblock %}

{% block customLinks %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/card.css') }}" />
{% endblock %}

{% block mainContent %}
<div id="deck">
    <div class="container deckDetails">
        {% if deck %}
            <h1 class="headline">
                {{ deck.name }}
                    <div class="float-end">
                        {% if deck.created_by_id == user.id %}
                            <a onclick="return confirm('Are you sure you want to delete?')" 
                                href="{{url_for('deck.delete_deck', deck_id=deck.id) }}"
                                class="btn updateProfile btn-secondary  d-inline-block float-end">
                                Delete Deck
                            </a>
                            <a href="{{url_for('card.add_card', deck_id=deck.id) }}" class="btn  me-3 mb-3 updateProfile  d-inline-block float-end">
                                Add Card
                            </a>
                            <button data-bs-toggle="modal" data-bs-target="#update_deck"
                                class="btn updateProfile mb-3 me-3  d-inline-block">
                                Update Deck
                            </button>
                        {% else %}
                            {% if cards|length > 0 %}
                                <a href="{{ url_for('card.download_excel', deck_id=deck.id) }}" class="btn ms-auto me-0 updateProfile h-50">
                                    Download Cards as Excel
                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
            </h1>
            <div class="deckRow">
                <div
                    class="container bg-white mb-3 d-flex align-items-center deck justify-content-between">
                    <div>
                        <h1>
                            {{ deck.name }}
                        </h1>
                        <p>
                            For
                            {{ deck.created_for.name if deck.created_for else 'All' }}
                        </p>
                    </div>
                    <div class="right-text">
                        <p>
                            {{ deck.number_of_cards }}
                        </p>
                        <h6>
                            ~By {{ deck.user.name }}
                        </h6>
                        <p class="small text-secondary ">At {{ deck.created_at.strftime(" %H:%M:%S, %d/%m/%Y") }}</p>
                    </div>
                </div>
            </div>
            
            {% if cards|length > 0 %}
                <a href="{{ url_for('review.review_form', deck_id=deck.id) }}" class="btn updateProfile mb-5 mt-5 mx-auto d-block w-25 p-2 fs-4">
                    Start Test
                </a>
            {% else %}
                <h6>No Questions Added</h6>
            {% endif %}
        {% if deck.created_by_id == user.id %}
            <div class="container">
                <div class="mb-5 d-flex align-items-end">
                    <form class="w-50 ms-0" action="{{ url_for('card.import_card', deck_id=deck.id) }}" enctype="multipart/form-data" method="POST">
                        <h6>Upload Excel</h6>
                        <div class="input-group">
                            <input type="file" class="form-control" id="file" 
                                aria-describedby="file" aria-label="Upload" 
                                required name="importFile"
                                accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, .xlsx, .xls">
                            <button class="btn btn-secondary" type="submit" id="file">Upload</button>
                        </div>
                    </form>
                    
                    {% if cards|length > 0 %}
                        <a href="{{ url_for('card.download_excel', deck_id=deck.id) }}" class="btn ms-auto me-0 updateProfile h-50">
                            Download Cards as Excel
                        </a>
                    {% endif %}
                </div>
                <div class="row">
                    {% for card in deck.cards.all() %}
                        <div class="mb-3 card col-lg-4 col-md-4 col-sm-6 col-xs-12">
                            <div class="card-body" style="min-height: 8em;">
                                <h1 class="fs-5">{{ card.front }}</h1>
                            </div>
                            <div class="card-footer bg-transparent">
                                <a href="{{ url_for('card.edit_card', card_id=card.id) }}" class="btn mb-2 updateProfile d-block">
                                    Edit Card
                                </a>
                                <a onclick="return confirm('Are you sure you want to delete?')" href="{{ url_for('card.delete_card', card_id=card.id, deck_id=deck.id) }}" class="btn updateProfile btn-secondary d-block">
                                    Delete Card
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

            <div class="modal fade" id="update_deck" aria-labelledby="update_deckLabel" aria-hidden="true" tabindex="-1">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Update {{deck.name}}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form name="updateForm" class="needs-validation" novalidate action="{{ url_for('deck.update_deck', deck_id=deck.id) }}"
                            method="POST">
                            <div class="modal-body">
                                <div class="mb-3">
                                    <input type="text" name="user_id" hidden value="{{user.id}}">
                                    <label for="name" class="form-label">Name</label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name" value="{{deck.name}}" required>
                                    <div class="invalid-feedback">
                                        Please enter valid name
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Tag</label>
                                    <div class="d-flex justify-content-start">
                                        <div>
                                            <input class="form-check-input" type="radio" name="created_for" 
                                                {% if deck.created_for.value == "1" %}checked{% endif %} 
                                                value="STUDENT" id="student">
                                            <label class="form-check-label" for="student">
                                                Student
                                            </label>
                                        </div>
                                        <div  class="ms-4">
                                            <input class="form-check-input" type="radio" name="created_for"
                                                {% if deck.created_for.value == "2" %}checked{% endif %}
                                                value="TEACHER" id="teacher">
                                            <label class="form-check-label" for="teacher">
                                                Teacher
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="status" class="form-label">Public</label>
                                    <select class="form-select" id="status" name="public_status" aria-label="Default select example" required>
                                        <option value="1" {% if deck.public_status %}selected{% endif %}>True</option>
                                        <option value="0" {% if not deck.public_status %}selected{% endif %}>False</option>
                                    </select>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% endif %}
        {% else %}
            <div class="deckRow text-center">
                <h1 class="">No Deck Found!</h1>
                <p class="text-secondary">Please check id</p>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block scriptsLinks %}
<script>

    
var forms = document.querySelector('form[name="updateForm"]')
if(forms){
    forms.addEventListener('submit', function (event) {
        if (!forms.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
        }
        forms.classList.add('was-validated')
    }, false)
}
</script>
{% endblock %}